"""
A single cell ATACseq analysis pipeline.
Author: Ming (Tommy) Tang  06/02/2020
"""

configfile: "config.yaml"

#include: "rules/common.snakefile"
# load the samples.json file
FILES = json.load(open(config['SAMPLES_JSON']))
ALL_SAMPLES = sorted(FILES.keys())


TARGET = []

PEAK_COUNT = expand("Result/Analysis/{sample}/{sample}_peak_count.h5", sample = ALL_SAMPLES)
PEAK_BATCH_COUNT = expand("Result/Analysis/Batch/{sample}/{sample}_peak_count.h5", sample = ALL_SAMPLES)


TARGET.extend(PEAK_COUNT)

if config.get("batch"):
	TARGET.extend(PEAK_BATCH_COUNT)

rule all:
	input: TARGET

if config["platform"] == "10x-genomics":
	include: "./rules/sc_atac_map.smk"
	include: "./rules/sc_atac_preprocess.smk"
	include: "./rules/sc_atac_fragment_generate.smk"
	include: "./rules/sc_atac_qc.smk"
	include: "./rules/sc_atac_peak_call.smk"
	include: "./rules/sc_atac_peak_count.smk"
	if config.get("batch"):
		include: "./rules/sc_atac_peak_count_batch.smk"
